services:
  - type: web
    name: recipe-book
    runtime: python3
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install Flask Flask-SQLAlchemy Flask-Login gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
